/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diem;

import form_chinh.f_chinh_gv;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import monhoc.MonHoc;
import monhoc.truyvandulieu_mh;
import ql_sv.xuly_sv;
import ql_sv.SinhVien;

/**
 *
 * @author admin
 */
public class f_Quanlydiem extends javax.swing.JFrame {

    /**
     * Creates new form f_Quanlydiem
     */
    truyvandulieu_diem diemdao = new truyvandulieu_diem();
    public f_Quanlydiem() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadCombos();
        loadTable();
       
        
    }
    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tblDiem.getModel();
    model.setRowCount(0);
    List<Diem> list = diemdao.getAll();
    int stt = 1;
    for (Diem d : list) {
        model.addRow(new Object[]{
            stt++, 
            d.getMaSV(), 
            d.getTenSV(), 
            d.getMaLop(), 
            d.getMaMH(),  
            d.getTenMH(), 
            d.getDiemTP1(), 
            d.getDiemTP2(), 
            d.getDiemCuoiKi(), 
            d.getDiemTongKet()
        });
    }
    }
    private void loadCombos() {
    
    cboSinhVien.removeAllItems();
    cboMonHoc.removeAllItems();
    cboMaLop.removeAllItems();

    // Thêm dòng mặc định để người dùng dễ chọn (Index 0)
    cboSinhVien.addItem("--- Chọn Mã SV ---");
    cboMaLop.addItem("--- Chọn Mã Lớp ---");
    cboMonHoc.addItem("--- Chọn Mã Môn ---");

    try {
        // 2. Load danh sách Sinh Viên và Mã Lớp từ lớp xuly_sv
        xuly_sv svdao = new xuly_sv(); 
        List<SinhVien> dsSV = svdao.getALL(); 
        
        // Sử dụng Set để lọc các mã lớp trùng nhau
        java.util.Set<String> setMaLop = new java.util.HashSet<>();

        if (dsSV != null) {
            for (SinhVien sv : dsSV) {
                // Thêm Mã SV vào ComboBox
                cboSinhVien.addItem(sv.getMaSV());
                
                // Lấy mã lớp từ sinh viên và cho vào Set (Set sẽ tự loại bỏ trùng lặp)
                if (sv.getMaLop() != null && !sv.getMaLop().isEmpty()) {
                    setMaLop.add(sv.getMaLop());
                }
            }
        }

        // Đổ danh sách mã lớp đã lọc (không trùng) vào ComboBox Mã Lớp
        for (String ml : setMaLop) {
            cboMaLop.addItem(ml);
        }

        // 3. Load danh sách Môn Học từ lớp truyvandulieu_mh
        truyvandulieu_mh mhdao = new truyvandulieu_mh();
        List<MonHoc> dsMH = mhdao.getAll();
        
        if (dsMH != null) {
            for (MonHoc mh : dsMH) {
                cboMonHoc.addItem(mh.getMaMH());
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi load dữ liệu vào ComboBox: " + e.getMessage());
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboSinhVien = new javax.swing.JComboBox<>();
        cboMonHoc = new javax.swing.JComboBox<>();
        txtDiemTP1 = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboMaLop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtDiemCuoiKi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiemTP2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quản lý điểm");

        tblDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SV", "Họ Tên", "Mã Lớp", "Mã Môn", "Tên Môn", "TP1", "TP2", "CK", "Tổng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiem);
        if (tblDiem.getColumnModel().getColumnCount() > 0) {
            tblDiem.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblDiem.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblDiem.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblDiem.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblDiem.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblDiem.getColumnModel().getColumn(6).setPreferredWidth(40);
            tblDiem.getColumnModel().getColumn(7).setPreferredWidth(40);
            tblDiem.getColumnModel().getColumn(8).setPreferredWidth(40);
            tblDiem.getColumnModel().getColumn(9).setPreferredWidth(45);
        }

        jLabel1.setText("Sinh Viên :");

        jLabel2.setText("Môn Học :");

        jLabel3.setText("Điểm  TP1:");

        cboSinhVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSinhVienActionPerformed(evt);
            }
        });

        cboMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonHocActionPerformed(evt);
            }
        });

        txtDiemTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTP1ActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã Lớp :");

        cboMaLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaLopActionPerformed(evt);
            }
        });

        jLabel6.setText("Điểm  TP2:");

        txtDiemCuoiKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemCuoiKiActionPerformed(evt);
            }
        });

        jLabel7.setText("Điểm  Cuối kì:");

        txtDiemTP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnThem)
                .addGap(33, 33, 33)
                .addComponent(btnSua)
                .addGap(34, 34, 34)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addGap(35, 35, 35)
                .addComponent(btnLamMoi)
                .addGap(31, 31, 31)
                .addComponent(btnThoat)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(402, 402, 402))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiemTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemCuoiKi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiemTP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiemCuoiKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(btnLamMoi)
                            .addComponent(btnThoat))
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonHocActionPerformed

    private void tblDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiemMouseClicked
        int row = tblDiem.getSelectedRow();
        if (row >= 0) {
            // Lấy dữ liệu từ các cột tương ứng
            String maSV = tblDiem.getValueAt(row, 1).toString();
            String maLop = tblDiem.getValueAt(row, 3).toString();
            String maMH = tblDiem.getValueAt(row, 4).toString(); // Cột Mã MH mới thêm
            String TP1 = tblDiem.getValueAt(row, 6).toString();
            String TP2 = tblDiem.getValueAt(row, 7).toString();
            String CK = tblDiem.getValueAt(row, 8).toString();

            // Hiển thị lên các điều khiển
            cboSinhVien.setSelectedItem(maSV);
            cboMonHoc.setSelectedItem(maMH);
            cboMaLop.setSelectedItem(maLop);
            txtDiemTP1.setText(TP1);
            txtDiemTP2.setText(TP2);
            txtDiemCuoiKi.setText(CK);
            
            cboSinhVien.setEnabled(false);
            cboMaLop.setEnabled(false);
        }
    }//GEN-LAST:event_tblDiemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Kiểm tra các ô nhập liệu có trống không
    if (txtDiemTP1.getText().trim().isEmpty() || 
        txtDiemTP2.getText().trim().isEmpty() || 
        txtDiemCuoiKi.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ 3 đầu điểm!");
        return;
    }

    // 2. Lấy dữ liệu từ ComboBox và TextField
    String maSV = cboSinhVien.getSelectedItem().toString();
    String maMH = cboMonHoc.getSelectedItem().toString();
    String maLop = cboMaLop.getSelectedItem().toString(); 

    float tp1 = Float.parseFloat(txtDiemTP1.getText());
    float tp2 = Float.parseFloat(txtDiemTP2.getText());
    float ck = Float.parseFloat(txtDiemCuoiKi.getText());
    
    if (diemdao.isExisted(maSV, maMH)) {
        JOptionPane.showMessageDialog(this, 
            "Lỗi: Sinh viên " + maSV + " đã có điểm môn " + maMH + "!\n" +
            "Vui lòng chọn môn khác hoặc sử dụng chức năng Sửa.");
        return; // Dừng lại không thực hiện thêm mới
    }

    // 3. Kiểm tra miền giá trị điểm (0 - 10)
    if (tp1 < 0 || tp1 > 10 || tp2 < 0 || tp2 > 10 || ck < 0 || ck > 10) {
        JOptionPane.showMessageDialog(this, "Điểm phải nằm trong khoảng từ 0 - 10");
        return;
    }

    // 4. Tính điểm tổng kết theo công thức (ví dụ: 10% - 20% - 70%)
    float tongKet = (float) (tp1 * 0.1 + tp2 * 0.2 + ck * 0.7);
    tongKet = (float) (Math.round(tongKet * 10.0) / 10.0);

    // 5. Tạo đối tượng Diem và gán giá trị
    Diem d = new Diem();
    d.setMaSV(maSV);
    d.setMaMH(maMH);
    d.setMaLop(maLop);
    d.setDiemTP1(tp1);
    d.setDiemTP2(tp2);
    d.setDiemCuoiKi(ck);
    d.setDiemTongKet(tongKet);

    // 6. Gọi hàm update (hàm này đã sửa ở bước trước: nếu chưa có thì Insert, có rồi thì Update)
    if (diemdao.update(d)) {
        JOptionPane.showMessageDialog(this, "Lưu điểm thành công!\nTổng kết: " + tongKet);
        loadTable(); // Cập nhật lại bảng hiển thị
    } else {
        JOptionPane.showMessageDialog(this, "Lỗi khi lưu dữ liệu vào cơ sở dữ liệu!");
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Lỗi: Điểm phải là số thực (ví dụ: 7.5)!");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
}
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        cboMaLop.setEnabled(false);
       try {
    // 1. Kiểm tra không để trống cả 3 ô điểm
    if (txtDiemTP1.getText().trim().isEmpty() || 
        txtDiemTP2.getText().trim().isEmpty() || 
        txtDiemCuoiKi.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ TP1, TP2 và Điểm Cuối Kỳ!");
        return;
    }

    // 2. Lấy dữ liệu từ giao diện
    String maSV = cboSinhVien.getSelectedItem().toString();
    String maMH = cboMonHoc.getSelectedItem().toString();
    String maLop = cboMaLop.getSelectedItem().toString();
    
    // Lấy điểm từ các ô text
    float tp1 = Float.parseFloat(txtDiemTP1.getText());
    float tp2 = Float.parseFloat(txtDiemTP2.getText());
    float ck = Float.parseFloat(txtDiemCuoiKi.getText());

    // 3. Kiểm tra miền giá trị điểm (0 - 10)
    if (tp1 < 0 || tp1 > 10 || tp2 < 0 || tp2 > 10 || ck < 0 || ck > 10) {
        JOptionPane.showMessageDialog(this, "Tất cả các đầu điểm phải nằm trong khoảng từ 0 đến 10!");
        return;
    }

    // 4. Tính điểm Tổng Kết (Công thức: 10% - 20% - 70%)
    float tongKet = (float) (tp1 * 0.1 + tp2 * 0.2 + ck * 0.7);
    // Làm tròn lấy 1 chữ số thập phân
    tongKet = (float) (Math.round(tongKet * 10.0) / 10.0);

    // 5. Tạo đối tượng Diem và gán giá trị
    Diem d = new Diem();
    d.setMaSV(maSV);
    d.setMaMH(maMH);
    d.setMaLop(maLop);
    d.setDiemTP1(tp1);
    d.setDiemTP2(tp2);
    d.setDiemCuoiKi(ck);
    d.setDiemTongKet(tongKet);
   
    if (diemdao.update(d)) {
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!\nĐiểm tổng kết: " + tongKet);
        loadTable(); // Cập nhật lại bảng
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại kết nối!");
    }

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Lỗi: Điểm nhập vào phải là số thực (ví dụ: 8.5)!");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage());
}
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maSV = cboSinhVien.getSelectedItem().toString();
        String maMH = cboMonHoc.getSelectedItem().toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Xóa điểm môn này của SV " + maSV + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (diemdao.delete(maSV, maMH)) {
                loadTable();
                btnLamMoiActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        f_chinh_gv formChinh = new f_chinh_gv();
        formChinh.setVisible(true);
        formChinh.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtDiemTP1.setText("");
        txtDiemTP2.setText("");
        txtDiemCuoiKi.setText("");
        cboSinhVien.setEnabled(true);
        cboMaLop.setEnabled(true);
        if (cboSinhVien.getItemCount() > 0) cboSinhVien.setSelectedIndex(0);
        if (cboMonHoc.getItemCount() > 0) cboMonHoc.setSelectedIndex(0);
        if (cboMaLop.getItemCount() > 0) cboMaLop.setSelectedIndex(0);
        tblDiem.clearSelection();
        loadTable();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cboSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSinhVienActionPerformed
        // TODO add your handling code here:
        if (cboSinhVien.getSelectedIndex() <= 0) {
        cboMaLop.setEnabled(true);
        return;
    }

    String maSV = cboSinhVien.getSelectedItem().toString();
    // Gọi hàm getOne từ diemdao (truyvandulieu_diem)
    SinhVien sv = diemdao.getOne(maSV); 
    
    if (sv != null) {
        cboMaLop.setSelectedItem(sv.getMaLop()); 
        cboMaLop.setEnabled(false);             
    }
    }//GEN-LAST:event_cboSinhVienActionPerformed

    private void txtDiemTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTP1ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
DefaultTableModel model = (DefaultTableModel) tblDiem.getModel();
model.setRowCount(0);
List<Diem> listKetQua = new ArrayList<>();

// 2. Kiểm tra xem người dùng muốn tìm theo cái nào
if (cboSinhVien.getSelectedItem() != null && cboSinhVien.getSelectedIndex() > 0) {
    String maSV = cboSinhVien.getSelectedItem().toString();
    listKetQua = diemdao.getByMaSV(maSV);
    
} else if (cboMaLop.getSelectedItem() != null && cboMaLop.getSelectedIndex() > 0) {
    // Nếu không chọn SV mà chọn Lớp thì tìm theo Lớp
    String maLop = cboMaLop.getSelectedItem().toString();
    listKetQua = diemdao.getByMaLop(maLop);
    
} else {
    JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã Sinh Viên hoặc Mã Lớp để tìm kiếm!");
    return;
}

// 3. Đổ dữ liệu vào bảng
if (listKetQua == null || listKetQua.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu điểm phù hợp!");
} else {
    int stt = 1;
    for (Diem d : listKetQua) {
        model.addRow(new Object[]{
            stt++, 
            d.getMaSV(), 
            d.getTenSV(), 
            d.getMaLop(),        
            d.getMaMH(),  
            d.getTenMH(), 
            d.getDiemTP1(),      
            d.getDiemTP2(),      
            d.getDiemCuoiKi(),   
            d.getDiemTongKet()    
        });
    }
}
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cboMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaLopActionPerformed

    private void txtDiemCuoiKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCuoiKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemCuoiKiActionPerformed

    private void txtDiemTP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Quanlydiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaLop;
    private javax.swing.JComboBox<String> cboMonHoc;
    private javax.swing.JComboBox<String> cboSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDiem;
    private javax.swing.JTextField txtDiemCuoiKi;
    private javax.swing.JTextField txtDiemTP1;
    private javax.swing.JTextField txtDiemTP2;
    // End of variables declaration//GEN-END:variables

}
