/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chuyennganh;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class form_chuyennganh extends javax.swing.JFrame {
    
    xuly_chuyennganh xuly = new xuly_chuyennganh();
    DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_chuyennganh.class.getName());

    /**
     * Creates new form form_chuyennganh
     */
    public form_chuyennganh() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tbl_chuyennganh.getModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_chuyennganh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_macn = new javax.swing.JTextField();
        txt_tencn = new javax.swing.JTextField();
        txt_them = new javax.swing.JButton();
        txt_sua = new javax.swing.JButton();
        txt_xoa = new javax.swing.JButton();
        txt_tailai = new javax.swing.JButton();
        txt_quaylai = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Chuyên Ngành ");

        tbl_chuyennganh.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbl_chuyennganh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "Mã chuyên ngành", "Tên chuyên ngành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_chuyennganh.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_chuyennganhAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl_chuyennganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chuyennganhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_chuyennganh);
        if (tbl_chuyennganh.getColumnModel().getColumnCount() > 0) {
            tbl_chuyennganh.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Mã chuyên ngành  :");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Tên chuyên ngành :");

        txt_macn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txt_tencn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txt_them.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_them.setText("Thêm");
        txt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_themActionPerformed(evt);
            }
        });

        txt_sua.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_sua.setText("Sửa");
        txt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suaActionPerformed(evt);
            }
        });

        txt_xoa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_xoa.setText("Xóa");
        txt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xoaActionPerformed(evt);
            }
        });

        txt_tailai.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_tailai.setText("Tải Lại ");
        txt_tailai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tailaiActionPerformed(evt);
            }
        });

        txt_quaylai.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_quaylai.setText("Quay Lại");
        txt_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quaylaiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setText("Xóa trắng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_macn)
                            .addComponent(txt_tencn, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tailai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_quaylai)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_macn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tencn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_them)
                    .addComponent(txt_sua)
                    .addComponent(txt_xoa)
                    .addComponent(txt_tailai)
                    .addComponent(jButton1)
                    .addComponent(txt_quaylai))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_chuyennganhAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_chuyennganhAncestorAdded
        // TODO add your handling code here:
        int row = tbl_chuyennganh.getSelectedRow();
        if (row >= 0) {
            
            txt_macn.setText(model.getValueAt(row, 1).toString());
            txt_tencn.setText(model.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_tbl_chuyennganhAncestorAdded

    private void txt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_themActionPerformed
        // TODO add your handling code here:
        
        String ma = txt_macn.getText();
        String ten = txt_tencn.getText();

        if (ma.isEmpty() || ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
            return;
        }

        
        chuyennganh cn = new chuyennganh(0, ma, ten);
        if (xuly.insert(cn) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadData(); 
            txt_macn.setText("");
            txt_tencn.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi! Mã chuyên ngành có thể đã tồn tại.");
        }
    }//GEN-LAST:event_txt_themActionPerformed

    private void txt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suaActionPerformed
        // TODO add your handling code here:
        int row = tbl_chuyennganh.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
            return;
        }

       
        int id = Integer.parseInt(model.getValueAt(row, 0).toString());
        String ma = txt_macn.getText();
        String ten = txt_tencn.getText();

        chuyennganh cn = new chuyennganh(id, ma, ten);
        
        if (xuly.update(cn)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật!");
        }
    }//GEN-LAST:event_txt_suaActionPerformed

    private void txt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xoaActionPerformed
        // TODO add your handling code here:
        int row = tbl_chuyennganh.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!");
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(model.getValueAt(row, 0).toString());
            
            if (xuly.delete(id)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadData();
                txt_macn.setText("");
                txt_tencn.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi! Có thể chuyên ngành này đang có sinh viên học.");
            }
        }
    }//GEN-LAST:event_txt_xoaActionPerformed

    private void txt_tailaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tailaiActionPerformed
        // TODO add your handling code here:
        txt_macn.setText("");
        txt_tencn.setText("");
        loadData();
    }//GEN-LAST:event_txt_tailaiActionPerformed

    private void txt_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quaylaiActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Đóng form
        form_chinh.f_chinh_gv frmMain = new form_chinh.f_chinh_gv();
        frmMain.setLocationRelativeTo(null); // Hiện giữa màn hình
        frmMain.setVisible(true);
    }//GEN-LAST:event_txt_quaylaiActionPerformed

    private void tbl_chuyennganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chuyennganhMouseClicked
        // TODO add your handling code here:
        
        int i = tbl_chuyennganh.getSelectedRow();
        
        
        if (i >= 0) {
            
            txt_macn.setText(model.getValueAt(i, 1).toString());
            
            txt_tencn.setText(model.getValueAt(i, 2).toString());
        }
    }//GEN-LAST:event_tbl_chuyennganhMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_macn.setText("");
        txt_tencn.setText("");
        tbl_chuyennganh.clearSelection();
        txt_macn.requestFocus();
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new form_chuyennganh().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_chuyennganh;
    private javax.swing.JTextField txt_macn;
    private javax.swing.JButton txt_quaylai;
    private javax.swing.JButton txt_sua;
    private javax.swing.JButton txt_tailai;
    private javax.swing.JTextField txt_tencn;
    private javax.swing.JButton txt_them;
    private javax.swing.JButton txt_xoa;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        
        model.setRowCount(0); 
        List<chuyennganh> ds = xuly.getALL();
        for (chuyennganh cn : ds) {
            model.addRow(new Object[]{
                cn.getId(), 
                cn.getMaChuyenNganh(), 
                cn.getTenChuyenNganh()
            });
        }
    }
}
