/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form_chinh;


import dangnhap.form_dangnhap;
import taikhoan.doimatkhau;
import chuyennganh.form_chuyennganh;
import diem.f_Quanlydiem;
import monhoc.f_Quanlymonhoc;
import ql_lophoc.frmLop;
import ql_sv.frmSinhVien;

/**
 *
 * @author Admin
 */
public class f_chinh_gv extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(f_chinh_gv.class.getName());

    /**
     * Creates new form f_chinh_gv
     */
    public f_chinh_gv() {
        initComponents();
        this.setTitle("Quản lý điểm Sinh viên");
        
        
           this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuLop = new javax.swing.JMenuItem();
        MonHoc = new javax.swing.JMenuItem();
        mnuChuyenNganh = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        DiemSo = new javax.swing.JMenuItem();
        mnuHSSV = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form_chinh/qlsv.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuBar1.setName(""); // NOI18N

        jMenu2.setText("Tài Khoản");
        jMenu2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jMenu2ComponentRemoved(evt);
            }
        });

        jMenuItem2.setText("Đổi mật khẩu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Đăng xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Danh mục");

        mnuLop.setText("Lớp");
        mnuLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLopActionPerformed(evt);
            }
        });
        jMenu4.add(mnuLop);

        MonHoc.setText("Môn học");
        MonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonHocActionPerformed(evt);
            }
        });
        jMenu4.add(MonHoc);

        mnuChuyenNganh.setText("Chuyên ngành");
        mnuChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChuyenNganhActionPerformed(evt);
            }
        });
        jMenu4.add(mnuChuyenNganh);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("QL Sinh viên");

        DiemSo.setText("Điểm SV");
        DiemSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiemSoActionPerformed(evt);
            }
        });
        jMenu5.add(DiemSo);

        mnuHSSV.setText("Hồ sơ SV");
        mnuHSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHSSVActionPerformed(evt);
            }
        });
        jMenu5.add(mnuHSSV);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenu2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ComponentRemoved

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Bạn có chắc chắn muốn đăng xuất?", 
                "Đăng xuất", 
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
           
            this.dispose();
        
            form_dangnhap frmLogin = new form_dangnhap();
            frmLogin.setLocationRelativeTo(null); // Hiện giữa màn hình
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        doimatkhau doi = new doimatkhau();
  
        doi.setLocationRelativeTo(null);
    
        doi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        doi.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLopActionPerformed
        // TODO add your handling code here
        frmLop d = new frmLop();
        d.setLocationRelativeTo(null); 
        d.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuLopActionPerformed

    private void MonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonHocActionPerformed
        // TODO add your handling code here:
        f_Quanlymonhoc MH = new f_Quanlymonhoc();
        MH.setLocationRelativeTo(null); 
        MH.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        MH.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MonHocActionPerformed

    private void mnuChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChuyenNganhActionPerformed
        // TODO add your handling code here:
        form_chuyennganh CN = new form_chuyennganh();
        CN.setLocationRelativeTo(null); 
        CN.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CN.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_mnuChuyenNganhActionPerformed

    private void DiemSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiemSoActionPerformed
        // TODO add your handling code here:
        f_Quanlydiem d = new f_Quanlydiem();
        d.setLocationRelativeTo(null);
        d.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DiemSoActionPerformed

    private void mnuHSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHSSVActionPerformed
        // TODO add your handling code here:
        frmSinhVien d = new frmSinhVien();
        d.setLocationRelativeTo(null); 
        d.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuHSSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new f_chinh_gv().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DiemSo;
    private javax.swing.JMenuItem MonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mnuChuyenNganh;
    private javax.swing.JMenuItem mnuHSSV;
    private javax.swing.JMenuItem mnuLop;
    // End of variables declaration//GEN-END:variables
}
