/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form_chinh;

import bangdiem.BangDiemForm;
import bangdiem.GPAForm;
import bangdiem.ThongTinSinhVienForm;
import dangkyhocphan.DangKyFrame;
import dangkyhocphan.KetQuaFrame;
import dangkyhocphan.ThiLaiFrame;
import java.util.Locale;
import monhoc.f_Quanlymonhoc;

/**
 *
 * @author Admin
 */
public class f_sv extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(f_sv.class.getName());

    /**
     * Creates new form f_sv
     */
    public f_sv() {
        initComponents();
        this.setTitle("Sinh viên");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        dkhp = new javax.swing.JMenu();
        kqdk = new javax.swing.JMenu();
        dktl = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Tài khoản");

        jMenu3.setText("Đổi Mật Khẩu");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenu4.setText("Đăng Xuất");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Học Phần");

        dkhp.setText("Đăng ký học phần");
        dkhp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dkhpMouseClicked(evt);
            }
        });
        jMenu5.add(dkhp);

        kqdk.setText("Kết quả đăng ký");
        kqdk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kqdkMouseClicked(evt);
            }
        });
        jMenu5.add(kqdk);

        dktl.setText("Đăng ký thi lại");
        dktl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dktlMouseClicked(evt);
            }
        });
        jMenu5.add(dktl);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Điểm");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });

        jMenu7.setText("GPA");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu7);

        jMenu2.setText("Bảng Điểm");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu6.add(jMenu2);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Thông tin SV");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        
        taikhoan.doimatkhau1 frm = new taikhoan.doimatkhau1();
        
        
        frm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        
        frm.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn đăng xuất?", 
                "Đăng xuất", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            
            this.dispose();
            
            
            new dangnhap.form_dangnhap().setVisible(true);
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void dkhpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dkhpMouseClicked
            DangKyFrame dk = new DangKyFrame();
        dk.setLocationRelativeTo(null); 
        dk.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dkhpMouseClicked

    private void kqdkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kqdkMouseClicked
            KetQuaFrame kq = new KetQuaFrame();
        kq.setLocationRelativeTo(null); 
        kq.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        kq.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kqdkMouseClicked

    private void dktlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dktlMouseClicked
             ThiLaiFrame tl = new ThiLaiFrame();
        tl.setLocationRelativeTo(null); 
       tl.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dktlMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        BangDiemForm tl = new BangDiemForm();
        tl.setLocationRelativeTo(null); 
       tl.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tl.setVisible(true);
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
 
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        // TODO add your handling code here:
        ThongTinSinhVienForm tl = new ThongTinSinhVienForm();
        tl.setLocationRelativeTo(null); 
       tl.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tl.setVisible(true);
        
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
               // TODO add your handling code here:
        GPAForm tl = new GPAForm();
        tl.setLocationRelativeTo(null); 
       tl.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tl.setVisible(true);
        
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new f_sv().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dkhp;
    private javax.swing.JMenu dktl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu kqdk;
    // End of variables declaration//GEN-END:variables
}
